sudo: false
dist: xenial

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^[0-9]+.*$/

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
  global:
    - PLUGIN_SLUG=wenprise-pinyin-slug
    - SVN_REPO=https://plugins.svn.wordpress.org/$PLUGIN_SLUG/
    - GIT_REPO=https://github.com/iwillhappy1314/$PLUGIN_SLUG.git
    - MAINFILE="$PLUGIN_SLUG.php"
    - secure: joJXNNGbycz3YMkRojSvDF02i0ZRz5N0VhTwo+nG9Kp0uR1UaFJ6MCACrI/0woBqAI87l+KgCU9sH2L2aoyx/rg/HXcoOFvhkJfFn3svIj870kr1IERFpNSTsF1a7WQ0r8T59imsIzpAk9VayP75vj7hQ1NTTg6w6c3SItEsVXnn2q9671aAtEQFsn3PLaoqg52XnvyKXDfjpMipnZF4g28GonZ+Iiuz1r8u7klBRRRCpk5ILcR7yraq7WzWiYZRvAp0R0hqWOXKwGdF3TubM7dMqe1nV/svjpLK8cXpqfMTi51gkSC0TwnuAwRS+bBExR1F/v64IFrM9bZv0Oiy0VJC6Em0FJCn6iZNbf2BQuUw7Ec+4yRgUXafZWXp7rYCK4N/t6GDBEmIYaOJI/fhA9awwYWRCG1M6NHNFykiBfNXQBzkbrW7hQ9ihAHcd1j2d0g2mase4KNe+lF1FVr5JWpQ9kjZaabaEAq0wcLG2+zqD2VjRkFkyg4d+v9bGfmszssd9qyd/yVdAaGZdHsK0WXegJZt5CZpP6EkIJ581jwIUWraMeRmeC0YN0Qcc6accbxKy6LCygpIA861os2TqVkmyGCuBEfpVElztctC8jCFP9j3FvjZLRnV11m920ZxEPxV54o84gQD+2Kt2p5QWJk14vtJTTciZa3kHGGObvk=

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1
      dist: precise


before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi

#after_success: curl -L https://raw.githubusercontent.com/iwillhappy1314/deploy2wporg/master/deploy.sh | sh