name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          composer install --no-dev
          composer dump-autoload -o
      - name: Unit Test
        run: |
          sudo systemctl start mysql.service
          sudo chmod +x bin/install-wp-tests.sh
          bin/install-wp-tests.sh wordpress_test root 'root' localhost $WP_VERSION
          composer global require "phpunit/phpunit=4.8.*|5.7.*"
          phpunit
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}